root = "."
tmp_dir = "tmp"

[build]
pre_cmd = ["templ generate"]
cmd = "go build -o ./tmp/tmux-dashboard ."
full_bin = "./tmp/tmux-dashboard -addr 0.0.0.0:${TMUX_DASHBOARD_PORT}"
include_ext = ["go", "tpl", "tmpl", "templ", "html"]
exclude_regex = [".*_templ.go"]
exclude_dir = ["tmp", "vendor", ".git"]
exclude_file = ["views/views_templ.go"]
delay = 500

[log]
time = false

[misc]
clean_on_exit = true
